### ISSUE TITLE
Compilation failure when installing via pip

### ISSUE THREAD

**Issue by flying-sheep** [limix/liknorm-py#1]
When liknorm isn’t installed, this fails.

If liknorm is only used from this package, and not needed from other ones, it might be a good idea to bundle it within liknorm-py.

<details><summary>output</summary>

```c
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/machine.py -> build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/__init__.py -> build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/_build.py -> build/lib.linux-x86_64-3.5/liknorm
    running egg_info
    writing requirements to liknorm_py.egg-info/requires.txt
    writing liknorm_py.egg-info/PKG-INFO
    writing top-level names to liknorm_py.egg-info/top_level.txt
    writing dependency_links to liknorm_py.egg-info/dependency_links.txt
    reading manifest file 'liknorm_py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'liknorm_py.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.5/liknorm/test
    copying liknorm/test/test_liknorm.py -> build/lib.linux-x86_64-3.5/liknorm/test
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.5/liknorm._ffi.c'
    creating build/temp.linux-x86_64-3.5
    building 'liknorm._ffi' extension
    creating build/temp.linux-x86_64-3.5/build
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/icb/philipp.angerer/.local/include -I/home/icb/philipp.angerer/.local/include/python3.5m -c build/temp.linux-x86_64-3.5/liknorm._ffi.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/liknorm._ffi.o
    build/temp.linux-x86_64-3.5/liknorm._ffi.c:434:33: fatal error: liknorm/liknorm.h: No such file or directory
         #include "liknorm/liknorm.h"
                                     ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

</details

**Comment by flying-sheep** [comment]
Is this fixed?

**Comment by horta** [comment]
Sorry @flying-sheep , I closed without answering because I though you had forgotten.

I could bundle the C library liknorm in a python package but that would make the development of it more difficult (two repositories with the same C code), as it is not a trivial software. Also, I coded C library liknorm to be used by those using C/C++ too.

Therefore, I opted to facilitate the installation of C liknorm via conda and also via command-line: https://github.com/limix/liknorm

Can I ask for the reason why you would like to use pip only? Baside, of course, of being simpler to install I admit...

**Comment by flying-sheep** [comment]
if enough packages [automate the creation and upload of wheels](https://github.com/joerick/cibuildwheel), there’s no reason to use conda anymore. nowadays, many packages have wheels, so i don’t need the added complexity of a second environment with native and python libraries besides my system one.

you wouldn’t need to bundle the code into this repo, you’d just need to upload wheels.

**Comment by horta** [comment]
I havent heard about that tool. At the time I was building wheels it was a pain when doing the same for Windows. Thanks a lot, I will give it a shot!

**Comment by flying-sheep** [comment]
great! i never tried it because i don’t maintain a package needing compilation, but they advertise minimal configuration, so maybe it’s worth it!

**Comment by horta** [comment]
Hi @flying-sheep , thanks for holding on! I finally finished the pipeline for wheel deployinment: https://pypi.org/project/liknorm/#files

Would you mind having it a go? It is the liknorm version 1.1.6.

**Comment by flying-sheep** [comment]
Ah damn, I thought I had sent this before.

works great on linux, i can’t say anything about windows though.

seems like it was lots more work than they promise, i’m sorry for that!

**Comment by horta** [comment]
No worries. It was worth it =)
